[pytest]
testpaths = 
    calculate_sum_and_product
    has_pair_with_sum
    has_pair_with_sum_sorted
    find_common_items

python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts = -v --tb=short 